name: CI/CD Pipeline

on:
    push: 
        branches: [ main ]

jobs:
    commande-de-base:
        runs-on: ubuntu-latest
    
        steps:
            - name: create folder
              run: mkdir newFolder

    test-job:
        runs-on: ubuntu-latest
        needs: commande-de-base
        steps:
            - name: list folders
              run: ls -l